### ISSUE TITLE
setup geonode instance

### ISSUE THREAD

**Issue by gubuntu** [kartoza/gfdrr_oondra#1]
We need an instance of geonode dedicated to this project running on kartoza5 at http://staging.oondra.kartoza.com
- based on geonode source, not packages, because we might be making modifications
- default install to start with
- Kartoza best practice based on GeoSAFE project
- default geoserver backend

@NyakudyaA please share with @rischanlab what you did so far on your dev machine so that we end up working on the same code base. 

cc @timlinux

**Comment by rischanlab** [comment]
Hi @NyakudyaA is there any documentation or wiki of your work? so I can follow up. 

Thanks.

**Comment by NyakudyaA** [comment]
yes @rischanlab  can you set up a remote of my fork for the repo and see my notes

**Comment by gubuntu** [comment]
@rischanlab please also configure nginx on kartoza5 to default to staging.kartoza.com in case a virtualhost (such as this one) does not respond. Or which should be default @timlinux? Currently it's defaulting to the catalogue staging site.

**Comment by rischanlab** [comment]
Hi @gubuntu please see my PR. 

Now Geonode is running on the staging. But really I am still not clear about this whole project. :(
![screen shot 2016-07-08 at 10 38 15 pm](https://cloud.githubusercontent.com/assets/2235894/16692947/36c89f9a-455d-11e6-835b-7d2a6be5bff6.png)

Thanks

**Comment by timlinux** [comment]
> @rischanlab please also configure nginx on kartoza5 to default to staging.kartoza.com in case a virtualhost (such as this one) does not respond. Or which should be default @timlinux? Currently it's defaulting to the catalogue staging site.

Defaulting to staging.kartoza.com sounds fine too me.

**Comment by gubuntu** [comment]
Note this is supposed to be running from source, not packages, see OP

**Comment by rischanlab** [comment]
Hi @gubuntu about the staging domain. It seems the site already redirect to correct domain. 
something like these:
http://staging.sdsdsada.kartoza.com
http://staging.test-domain.kartoza.com
http://staging.redirect-to-staging.kartoza.com

**Comment by gubuntu** [comment]
@rischanlab and @NyakudyaA please try to get Geonode container(s) working properly (geoserver, ports, db container etc) before Rischan leaves. e.g. the Ash layer is giving pink tiles.

**Comment by NyakudyaA** [comment]
yes @gubuntu I told @rischanlab what to do.

**Comment by gubuntu** [comment]
@NyakudyaA you can now ssh into k5 to sort this out.
