### ISSUE TITLE
Download world pop data and ingest it in geonode

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/gfdrr_oondra#20]
Publish worldpop service (minimum coverage Tanzania) metadata

**Comment by gubuntu** [comment]
@Nyakudya please update this with what you did with the geoserver REST API and then describe the service that supersedes that (which @timlinux mentioned) where you can already get worldpop via a service.
- [ ] find and reference the inaSAFE metadata structure specification in a wiki page in OONDRA Github
- [x] then create a metadata record for the worldpop service in the oondra geonode instance according to that metadata specificiation

**Comment by NyakudyaA** [comment]
Downloading the data using the API created by samweli only produces vector output. The tool has already been incorporated into inasafe  [inasafe world pop integration ](https://github.com/Samweli/inasafe/tree/worldpop_integration)  but needs to be extended so that it can download world pop as raster layer.

![Population Downloader Icon](https://s32.postimg.org/x6ny5wynp/pop.png)

The source code for world pop api can be sourced from: [world pop api source code](https://github.com/codeforresilience/worldpop-api).

**Comment by timlinux** [comment]
Hi

Probably better to file an upstream ticket with Samweli too for this (if you didn't already).

Regards

Tim

**Comment by gubuntu** [comment]
@NyakudyaA please do items in https://github.com/kartoza/gfdrr_oondra/issues/20#issuecomment-229941270 today.

We do need worldpop as a raster layer for InaSAFE as a priority. @timlinux can we task (and subcontract?) Samweli to do this? We need it asap so if we can't bank on him to do it soon then we'll have to do it in-house (who would be best?).

**Comment by NyakudyaA** [comment]
I have uploaded all Tanzania raster and ingested them in inasafe. Updated the wiki for what what I have done and layer naming conventions

**Comment by gubuntu** [comment]
@NyakudyaA tick the outstanding item in https://github.com/kartoza/gfdrr_oondra/issues/20#issuecomment-229941270 asap then close

**Comment by NyakudyaA** [comment]
The only missing part is the integration of the samweli's inasafe branch and get the ui directly in inasafe or merging his branch into geosafe.

**Comment by gubuntu** [comment]
@NyakudyaA please read my comment carefully before closing
