### ISSUE TITLE
enable geonode to publish standalone metadata documents

### ISSUE THREAD

**Issue by gubuntu** [kartoza/gfdrr_oondra#22]
# Problem

In vanilla Geonode, a metadata document is always linked to a dataset stored in the Geonode backend.

There are many use cases, including this project, where we want it to function more like a generic metadata clearinghouse. So, many metadata records will refer to remote services or offline data sets and have no local dataset. 
# Proposed solution

Remove the dependency of metadata records on a backend data store. i.e. Enhance Geonode functionality as a pure pyCSW front-end.

Handle any consequences this change has.

**Comment by gubuntu** [comment]
@timlinux, @cchristelis who is the best person to tackle this?

**Comment by timlinux** [comment]
I think @ismailsunni but it is going to be a tight month time wise for him to work on it...

**Comment by gubuntu** [comment]
@timlinux does @ismailsunni have some time now to look at this?

**Comment by timlinux** [comment]
@gubuntu I'm sorry I can't take him off InaSAFE work right now - we have a tight deadline for mid nov to stick too....I think we need to get some more team members on board for this....

**Comment by gubuntu** [comment]
@Gustry ? @lucernae ? ...note support from Tom Kralidis

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geonode#332
