### ISSUE TITLE
Skin Geonode for OONDRA

### ISSUE THREAD

**Issue by gubuntu** [kartoza/gfdrr_oondra#24]
We need a distinctive look and feel for this portal to brand it and distinguish it from vanilla Geonode

Use design cues from InaSAFE and World Bank GFDRR Challenge resources

http://oondra.kartoza.com/

**Comment by gubuntu** [comment]
@dimasciput can you take a look at this this week?

**Comment by gubuntu** [comment]
Thanks @dimasciput, looks great. Please remind me in which repo the skin mod is stored (InaSAFE I think) and write a little wiki page on https://github.com/kartoza/gfdrr_oondra/ documenting which files you deployed where to apply the skin.
I'd like to change some text on the front page, it doesn't look like I can do that through admin, which file(s) do I need to edit?
@dimasciput do you think you can quickly put together a logo for OONDRA to replace the Geonode one? Something simple symbolising 'a hazard and exposure data feed'. Remember to book all time on this project to the iMMAP Challenge Fund project in Harvest.

**Comment by gubuntu** [comment]
@dimasciput please wrap this up to close asap. Communicate with @rischanlab as this relates to #48

**Comment by rischanlab** [comment]
Hi @dimasciput 
could you design the logo for OONDRA. 

I have changed the description of OONDRA live site except the logo. 

![screen shot 2016-11-23 at 10 08 31 am](https://cloud.githubusercontent.com/assets/2235894/20550097/d75cb3f6-b164-11e6-9920-adf0ee7c8997.png)

Thank you

**Comment by gubuntu** [comment]
@dimasciput @rischanlab OONDRA has reverted to vanilla Geonode. Please redeploy the skin with the OONDRA logo as a matter of urgency, in a repeatable way (i.e. with deployment code in the oondra repo). 

cc @cchristelis

**Comment by rischanlab** [comment]
I will close this issue. 
The logo created by @dimasciput 
Thanks dimas 
![screen shot 2016-11-29 at 6 08 12 pm](https://cloud.githubusercontent.com/assets/2235894/20707661/e11a953a-b65e-11e6-831a-b8f992d5d8a9.png)

**Comment by gubuntu** [comment]
Thanks @dimasciput and @rischanlab 

Except @rischanlab, the last line (in parentheses) was meant for you to check, not to display!
