### ISSUE TITLE
MetaSearch Search not working

### ISSUE THREAD

**Issue by gubuntu** [kartoza/gfdrr_oondra#26]
Metasearch service info (getcapabilities) is working with http://staging.oondra.kartoza.com/catalogue/csw but Search returns 
`Connection error: <urlopen error [Errno 111] Connection refused>`

Please investigate, this needs to work

**Comment by NyakudyaA** [comment]
I have got it working on my local machine. I will update staging with the changes I have done.

**Comment by NyakudyaA** [comment]
working properly now
