### ISSUE TITLE
We need an automated way to generate metadata

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/gfdrr_oondra#28]
# Problem

Currently ingesting layers in geonode allows you to preserve metadata that is already associated with a layer. Geonode also generates metadata for a layer which contains wcs ,wfs endpoints. So we need a way to automatically combine the two metadata documents to generate a single metadata with all the necessary information. 

We need to upload layers using geonode management commands 
    `python manage.py importlayers -m data_directory`  Which would preserve the correct metadata record
# Solution

Find automated solutions to generate / combine metadata from geoserver and metadata from inasafe
Look at [update metadata](https://gist.github.com/ingenieroariel/1440520)

**Comment by gubuntu** [comment]
for upstream geonode

**Comment by gubuntu** [comment]
@NyakudyaA please ensure the current workaround / best procedure is documented (state where). Also reference the  upstream Issue you created or commented on with this requirement, then close

**Comment by NyakudyaA** [comment]
Currently we uploading layers using geonode UI. [geonode_upload](https://github.com/kartoza/gfdrr_oondra/wiki/Uploading-layer-into-geonode)
