### ISSUE TITLE
Improve geonode metadata handling

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/gfdrr_oondra#29]
# Problem

When uploading a layer using the geonode api there is a preserve metadata option which works for preserving metadata generated by inasafe. 

 `python manage.py  importlayers`
- Using this option it then implies that geonode does not add it's own metadata details which 
  include wfs/wms/wcs endpoints.
- The metadata record uploaded this way  is locked. It cannot be further edited using the geonode ui.
# Solution

Tweak geonode to allow addition of  inasafe keywords for metadata that has been uploaded using the geonode api.
 Add geonode wfs/wms/wcs endpoint to a metadata record that has been uploaded using preserve
 method (geonode api)

**Comment by gubuntu** [comment]
This also needs to go upstream to Geonode. @lucernae please ask @NyakudyaA to claridy if you're not clear. Do this and #30 mesh with general geonode metadata improvements that @timlinux has been discussing?

**Comment by NyakudyaA** [comment]
We no longer need this because we are using geonode UI to upload keywords.  When uploading layers with the preserve option geonode guys say the only way to update  the metadata is to re import with a new metadata. They also say they have deliberately made the metadata not editable because they cannot figure out how the metadata being imported fits into their models. In our case importing with a metadata document from inasafe will not work because wfs/wcs/wms endpoints will not appear in the metadata record
