### ISSUE TITLE
Upload of remote  layers in Geosafe

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/gfdrr_oondra#31]
# Problem

Currently no method exist to fetch layers + metadata from http://oondra.kartoza.com/
# Solution

Implement a method to fetch layers in external geonode. On upload layer in geosafe add url parameter to fetch layer so that analysis can be run

**Comment by gubuntu** [comment]
@lucernae is busy with this

**Comment by lucernae** [comment]
layers can be fetched and I've been busy with trying to extract metadata using CSW. This past few days I finally got the click on understanding it.
For now I suggests we embed InaSAFE keywords in the supplementalInformation described here: 
#30

**Comment by gubuntu** [comment]
@lucernae please comment on status and fix or close

**Comment by gubuntu** [comment]
was done with 'Metasearch' plugin
