### ISSUE TITLE
publish OSM flood data through OONDRA Geonode

### ISSUE THREAD

**Issue by gubuntu** [kartoza/gfdrr_oondra#34]
Community-mapped inundation data for Dar es Salaam is stored in OSM according to [link to doc from Mark Iliffe] and can be retrieved with this overpass query [query to be provided by Mark Iliffe].

We need to use kartoza/docker-osm to maintain a local copy of these on the OONDRA server and publish them through the OONDRA Geonode. 

in other words, they will not be traditional Geonode layers but are a perfect example of making a hazard data 'feed' available through the oondra platform. 
- OONDRA Geonode metadata and OWS endpoints need to be dynamically maintained to match the flood layers in the docker-osm database.

**Comment by NyakudyaA** [comment]
@gubuntu  The flood data I published I got it from such an overpass by Samweli

**Comment by NyakudyaA** [comment]
I have published the osm data through geoserver and it is available in oondra
