### ISSUE TITLE
load and publish Dar flood dems

### ISSUE THREAD

**Issue by gubuntu** [kartoza/gfdrr_oondra#36]
this refers to dems and point clouds of Dar es Salaamfrom Mark Iliffe

these are not directly hazard layers but can be used as WMS basemaps or WCS inputs into certain impact functions?  

This relates to (depends on) successful stitching of adjacent DEMS and subsequent probabilistic flood models being generated, which must in turn be published on oondra.

**Comment by gubuntu** [comment]
@NyakudyaA please comment - these layers are in the WB Box folders. Once loaded please comment on which layers they are in OONDRA then close

**Comment by NyakudyaA** [comment]
All flood layers from [Flood]( https://app.box.com/files/0/f/11632942697/Flood_1m) have been loaded in oondra and they are named Dar es Salaam Flood (depth)M in oondra.  Other layers from  #50 
have been loaded.

**Comment by gubuntu** [comment]
where are the DEMS?

**Comment by NyakudyaA** [comment]
http://staging.oondra.kartoza.com/layers/geonode:dar_flood_1m. These are the Flood DEMS

**Comment by gubuntu** [comment]
nope those are flood models. There are separate DEM layers. I'll leave this open but please leave the OONDRA work for now.
