### ISSUE TITLE
publish gridded world population

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/gfdrr_oondra#38]
# Problem

Manually download the various population datasets from [gridded pop](http://sedac.ciesin.columbia.edu/data/collection/gpw-v3/sets/browse). There are various resolution and all these need to be incorporated downloaded and given names which are descriptive
# Solution

To ingest these datasets in geonode they need to have keywords generated. Import them into QGIS and generate keywords using INASAFE. Once the keywords have been generated the data needs to be uploaded into oondra using geonode api which preserves the keywords

**Comment by NyakudyaA** [comment]
will publish all the other resolutions with well defined names

**Comment by gubuntu** [comment]
@NyakudyaA  please comment on progress and do some other ones or close. You could also publish one or more of the FaceBook / CIESIN countries that have been released (#39; low priority, since Tanzania hasnot been released yet)

**Comment by NyakudyaA** [comment]
have populated them with metadata. Will look at #39 next
