### ISSUE TITLE
Previewing the layer before fetching it to GeoSAFE

### ISSUE THREAD

**Issue by lucernae** [kartoza/gfdrr_oondra#41]
For WFS, I think it is possible to preview the layer in the Add Layer dialog in GeoSAFE.
I tried to use json request but it got denied because of cross origin requests.
So, I read that, in order for GeoSAFE to be able to preview staging oondra's WFS layer, we need to enable jsonp output format.
This is the article I mentioned [http://gis.stackexchange.com/questions/64406/getting-wfs-data-from-geoserver-into-leaflet](http://gis.stackexchange.com/questions/64406/getting-wfs-data-from-geoserver-into-leaflet).
This is not really mandatory for fetching the layers, but I think it would help the user if they are able to see the layer when trying to filter the extent.

For WCS, I haven't found a way to get the preview in leaflet. But perhaps it can be done using WMS just to preview it if it supports.

CC @NyakudyaA @gubuntu

**Comment by NyakudyaA** [comment]
@lucernae  Is this still relevant

**Comment by lucernae** [comment]
It works for WMS layer now (it was displayed in preview).
For WFS, I haven't found any way to display it to preview. Possible way is to enable JSONP in WFS, and have GeoSAFE displayed it using JSONP.
So for WFS, we're not able to show the preview.

**Comment by gubuntu** [comment]
WMS can (and should) be used for previews in all cases

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geonode#331
