### ISSUE TITLE
create new map not working in geonode

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/gfdrr_oondra#45]
# Problem

When in layer preview mode trying to generate  a map results in `504 Gateway Time-out
nginx/1.6.2 ` error .

# Solution

Geoexplorer seems to be using the internal ip address inside the docker container. This makes it impossible to access layers from geoserver external ip.  Adding a server `http://localhost:8080/geoserver/wms` results in the layers being accessible but they are however pink tiles because the request that is being generated is wrong.

![url](https://cloud.githubusercontent.com/assets/2510900/20057833/75cf7a4e-a4f6-11e6-984b-79074db5fc71.png)

Investigate correct ways to proxy the url inside the docker container. Look at `docker-geonode/pavement.py ` and geonode proxy

**Comment by rischanlab** [comment]
Hi @NyakudyaA Is this issue already fixed? 

I open Geoserver on the staging then see layer preview everything working fine. 
Or maybe I missunderstand with this issue. 
Could you confirm it Admire? 

Thank you

**Comment by gubuntu** [comment]
@NyakudyaA @rischanlab from what you report, this is working now. Please reopen if not.
