### ISSUE TITLE
configure nginx for production site

### ISSUE THREAD

**Issue by gubuntu** [kartoza/gfdrr_oondra#46]
Since we don't really need a staging site for oondra and we're at the end of the project, please configure k5 nginx where http://staging.oondra.kartoza.com is currently accepting requests to also accept requests at http://oondra.kartoza.com

**Comment by rischanlab** [comment]
Hi @gubuntu I have edited nginx conf on Kartoza5 to accept [http://oondra.kartoza.com](http://oondra.kartoza.com), but it seems that domain did not pointed to Kartoza5 yet. 

![screen shot 2016-11-14 at 1 56 34 pm](https://cloud.githubusercontent.com/assets/2235894/20255840/56352c7a-aa72-11e6-88cc-20e38a97dc24.png)

Thank you

**Comment by gubuntu** [comment]
oondra and staging.oondra are both pointing to k5. CDN was switched on for oondra, that's why you got a different IP address. I have switched off CDN now so it should ping k5, but that still doesn't fix the nginx config issues

**Comment by rischanlab** [comment]
Its done @gubuntu
