### ISSUE TITLE
Make oondra layers and metadata usable in Inasafe QGIS

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/gfdrr_oondra#47]
# Problem

We need a user to be able to download a layer with it's associated metadata and be directly usable in Inasafe in QGIS. 

# Solution

Do not escape the metadata in the client side. Metadata should be properly formatted to conform with the geonode format before uploading it into geonode or at the insertion point into the database.

**Comment by gubuntu** [comment]
@NyakudyaA is there something @lucernae must do here? Or it is a matter of you finding out from Rizky how to structure the metadata so that it works in QGIS and GeoSAFE?

**Comment by NyakudyaA** [comment]
Currently working with remote layers in inasafe and using their metadata is not possible as [https://github.com/inasafe/inasafe/issues/3475](url). The only way will be to download the layer and it's metadata. No method or plugin currently exist to allow downloading of metadata

**Comment by NyakudyaA** [comment]
@lucernae  we need to properly format the metadata either when it is ingested in the database or in the geonode gui. I will close this this ticket and open a new one #56
