### ISSUE TITLE
Make metasearch intutive in geosafe

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/gfdrr_oondra#49]
# Problem

Currently the only way you can search for records using metasearch is by having to know the url for csw and also the search uses keywords as the main criteria. There is no way to list all layers coming from oondra. When a csw request is done it should give a list of all layers if there are no keywords specified.

# Solution
Allow a user to search metadata without typing the keywords. This should return a full list of layers in the catalog. 
Create a dropdown with a list of csw url that has got a list of layers for inasafe and other live feeds.

**Comment by gubuntu** [comment]
Make this an upstream geosafe ticket?

**Comment by NyakudyaA** [comment]
after testing again. It seems the search is working properly now without keywords.
