### ISSUE TITLE
populate metadata

### ISSUE THREAD

**Issue by gubuntu** [kartoza/gfdrr_oondra#52]
Metadata for most if not all layers is very incomplete (this should have been done when loading the layer). e.g. http://oondra.kartoza.com/layers/geonode:population_density_adjusted_to_2015_country_totals_2015/metadata_detail

For ALL layers, these MUST be present:
- abstract
- owner information (who owns the data; where did we get it from; attribution)
- thumbnail (why not appearing in above link and others?) - @rischanlab pls investigate
- spatial resolution (if raster)
- Contact points (who to contact to find out more about the data or to get the source data)
- some Data Quality comments if possible. 
- Metadata author (you)

**Comment by NyakudyaA** [comment]
@gubuntu  what is the contact point, and owner information is it the source of the data

**Comment by NyakudyaA** [comment]
i have populated the metadata. just need to stop and restart the container again

**Comment by gubuntu** [comment]
can you do that? If not ask @rischanlab 

@rischanlab please confirm that backups are operational.

**Comment by rischanlab** [comment]
Hi @gubuntu  I saw all docker gfdrr containers start 6 hours ago. 
It seems @NyakudyaA has been restarted the containers. 

I think everything is working fine. 
But for the http://staging.oondra.kartoza.com/catalogue/csw?outputschema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&service=CSW&request=GetRecordById&version=2.0.2&elementsetname=full&id=5f8987b4-aff7-11e6-a16d-0242ac110025

thumbnails url still contain localhost. 

cc @NyakudyaA

**Comment by NyakudyaA** [comment]
@rischanlab Already updated metadata will not be updated by the changes. Its for new data that will  be uploaded that will have the new changes. I have updated the old ones to have the new changes. I will try to upload a new dummy layer and see if the changes work

**Comment by rischanlab** [comment]
Ok @NyakudyaA 👍 
waiting to see the dummy layer.

**Comment by gubuntu** [comment]
@NyakudyaA many layers still do not have metadata, e.g. World population density
