### ISSUE TITLE
Properly format metadata so that it is usable in QGIS inasafe

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/gfdrr_oondra#56]
# Problem 
Currently the only way to upload metadata into geonode is using the geonode UI. This however returns metadata which is not properly formated as indicated below:

![inasafe_orig](https://cloud.githubusercontent.com/assets/2510900/20562028/3d1407ce-b18a-11e6-8612-dc7b4ac6053a.png)

The above is what you see in the browser when you click the download metadata. As seen in this request: [http://staging.oondra.kartoza.com/catalogue/csw?outputschema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&service=CSW&request=GetRecordById&version=2.0.2&elementsetname=full&id=82e5facf-ae89-417f-8192-c7678a98c7a9](url)

As opposed to the original/raw metadata file generated by insafe as seen below:

![insafe_two](https://cloud.githubusercontent.com/assets/2510900/20562080/86343c30-b18a-11e6-8c39-007cf93019c7.png)

So when you download the layer and the metadata so that you can use it in QGIS inasafe it is unusable because the metadata is not properly formated  to inasafe standards as noted below:

![inasafe_improp](https://cloud.githubusercontent.com/assets/2510900/20562247/4a2e8802-b18b-11e6-963d-3ace12d47144.png)

There seem to be some tags that are added by geonode which inasafe does not understand hence rendering the metadata invalid.

[metada_xml.zip](https://github.com/kartoza/gfdrr_oondra/files/608882/metada_xml.zip)
Attached are three files that relate to osm_flood_current.

* osm_current_flood_inasafe_qgis.xml - Is the original xml file generated by inasafe on the raw 
  layer before uploading to geonode
* osm_current_flood_oondra.xml - Is the metadata layer that is downloaded from oondra
   in its current state. This has metadata improperly  structured.
* osm_current_flood_modified_after_download.xml -This is the metadata after modifications 
  by comparing the metadata generated by inasafe before uploading to geonode with 
  the metadata downloaded from oondra

**NB** I haven't tested the current metadata format to see if it works directly on running analysis 
          in  geosafe. The last time I tried geosafe. It recognized the oondra layers as inasafe layers
          with metadata in it's current format.

**Comment by NyakudyaA** [comment]
@lucernae  I have tested this on my local machine and it works fine now. I can now return all properly formatted metadata.  [metadata structure](https://github.com/kartoza/gfdrr_oondra/wiki/Ingesting-data-into--Geonode#metadata-structure). I haven't deployed on oondra yet. If @rischanlab  can test first on his machine to confirm.

![kewy](https://cloud.githubusercontent.com/assets/2510900/20627277/a61fb170-b327-11e6-87ba-24563910298a.png)

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geonode#270
