### ISSUE TITLE
server maintenance

### ISSUE THREAD

**Issue by gubuntu** [kartoza/gfdrr_oondra#62]
1. remove geonode instance from crevice (196.214.55.117). This used to be geosafe.kartoza.com.
2. Move production OONDRA geonode from kartoza5 (213.133.111.115) to crevice (196.214.55.117) or to another capable host (@timlinux?). oondra.kartoza.com is already pointing to crevice. 
 - upgrade to vanilla Geonode 2.6 (Geoserver)
 - ensure all OONDRA data comes across successfully
 - Note that staging was also on kartoza5 - make sure you migrate production, not staging. 
1. When satisfied that OONDRA production data has been migrated 100%, remove old oondra staging and production from kartoza 5.

**Comment by timlinux** [comment]
Yeah we should do a review of what is running on those old laptops in the server cabinet and then use then for staging / testing rancher etc. Otherwise lets spin it up on a VPS if needed.

**Comment by gubuntu** [comment]
http://oondra.kartoza.com production is successfully running on a Kartoza Hetzner DE server
